Repository matheus-fraga/quiz, pull requests merged in 2023-08, with the labels that each got.

#46 Slider volume
  index.html
  js/musicPlayer.js
  js/script.js
Labels: enhancement

#48 Aplicando as funções criadas
  css/results-dark.css
  css/results-light.css
  js/changeScreen.js
  js/databaseResults.js
  js/results.js
  js/savePlayer.js
  js/script.js
  js/showQuestions.js
  js/timer.js
  js/verifyQuestions.js
Labels: documentation

#50 Correção de bug
  css/global.css
  index.html
  js/changeScreen.js
  js/script.js
  js/showQuestions.js
Labels: bug

#56 Fixado barra superior da tela de Resultados
  css/results-dark.css
  css/results-light.css
Labels: enhancement

#58 Adicionando Elementos finais no results
  js/changeScreen.js
  js/databaseResults.js
  js/results.js
Labels: enhancement

#59 adicionando mediaQuery
  css/global.css
  css/index-dark.css
  css/index-light.css
  css/medias-query.css
  css/quiz-dark.css
  css/quiz-light.css
  index.html
Labels: bug, enhancement

#61 Average para porcentagem
  js/results.js
Labels: enhancement
