Repository matheus-fraga/quiz, pull requests merged in 2023-07, with the labels that each got.

#8 Criar HTML e perguntas do QUIZ
  js/css.js
  js/html.js
  js/js.js
  js/script.js
  js/tema_css.js
  js/tema_html.js
  js/tema_js.js
  view/quiz.html
Labels: documentation

#9 Pagina inicial
  index.html
Labels: documentation

#10 adicionado arquivo html da pagina resultado
  view/resultados.html
Labels: enhancement

#11 Criado a estilização da pagina login
  css/index.css
  index.html
Labels: documentation

#13 definindo a paleta de cores do global css
  css/global.css
Labels: documentation

#15 estilizacao pagina quiz
  css/global.css
  css/quiz.css
  view/quiz.html
Labels: documentation

#17 arrumando as perguntas html
  js/tema_html.js
Labels: bug

#18 adicionado script reprodutor de musica, adicionado estilo botao e arq…
  css/index.css
  index.html
  js/musicPlayer.js
  js/script.js
  music/music.mp3
Labels: enhancement

#27 criado overflow da tabela reultado
  css/resultados.css
  view/resultados.html
Labels: documentation

#28 arrumando a dimencao da tela quiz
  css/global.css
  css/quiz.css
  view/quiz.html
Labels: bug, documentation

#30 adicionando script para quiz
  js/script.js
  js/showQuestions.js
  js/verifyQuestions.js
Labels: documentation

#31 Criado funcao array resultados
  js/results.js
  js/script.js
  js/showQuestions.js
  view/resultados.html
Labels: enhancement

#32 criado funcao encontrar 5 melhores notas de cada tema
  css/resultados.css
  js/results.js
  js/script.js
  view/resultados.html
Labels: enhancement

#33 Tema
  css/global.css
  css/index-dark.css
  css/index-light.css
  css/quiz-dark.css
  css/quiz-light.css
  css/resultados-dark.css
  index.html
  js/script.js
  js/toggleTheme.js
  js/user_name_storage.js
Labels: enhancement

#34 Funcionalidade do site, Juntando funções, e criando intercessões
  css/global.css
  css/index-dark.css
  css/index-light.css
  css/quiz-dark.css
  css/quiz-light.css
  css/results-dark.css
  css/results-light.css
  index.html
  js/changeScreen.js
  js/databaseResults.js
  js/musicPlayer.js
  js/results.js
  js/script.js
  js/showQuestions.js
  js/theme_css.js
  js/theme_html.js
  js/theme_js.js
  js/toggleTheme.js
  js/user_name_storage.js
  js/verifyQuestions.js
  view/resultados.html
Labels: enhancement

#35 Correção de Bugs
  js/showQuestions.js
Labels: bug

#43 Timer1
  js/timer.js
Labels: documentation

#44 adicionando a funcao de desabilitar formulario e refatorando o codigo
  js/verifyQuestions.js
Labels: documentation, enhancement

#45 fixado th de resultados e atualizado css dark results
  css/results-dark.css
  css/results-light.css
  js/changeScreen.js
  js/results.js
Labels: enhancement
